name: Test Scripts

on:
  push:
    branches: 
      - main
    paths:
      - ".github/workflows/*"
      - "my_tools/*"
      - "MIT*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Modify variables for testing
      shell: powershell
      run: |
        # Disable Clear-HostLine in downloader.psm1
        $downloaderPath = ".\my_tools\downloader.psm1"

        $oldString = @"
            Clear-HostLine $Line
        "@

        $newString = @"
            # Clear-HostLine $Line
        "@

        (Get-Content -Path $downloaderPath -Raw) -replace $oldString, $newString | Set-Content -Path $downloaderPath

        # Replace my-config.json
        Copy-Item -Path ".\my_tools\test\my-config.json" -Destination ".\examples\" -Recurse -Force

        # Replace folder selection with regular path string
        $filePath = @(
            ".\MIT-local-launcher.ps1",
            ".\MIT-local-webtoon-launcher.ps1"
        )

        $findPattern = @"
        (?s)Select folder with FolderBrowserDialog.*Activate Python venv with another PowerShell script
        "@

        $replaceText = @'

            $InputPath = ".\my_tools\test\manga\RAW\"

        '@

        foreach ($path in $filePath) {
            (Get-Content -Path $path -Raw) -replace $findPattern, $replaceText | Set-Content -Path $path
        }

    - name: Run MIT-installer.ps1
      shell: powershell
      run: |
        # Change Execution Policy for Pyenv Windows
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine

        Write-Host "$(where.exe python)`n"

        # Run the installer
        .\MIT-installer.ps1

        $ErrorLogPath = ".\Temp\log_errors-install.txt"

        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                $ErrorLog
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

        Write-Host "`n$(python --version)"

        Write-Host "`n$(where.exe python)"

    - name: Run MIT-local-launcher.ps1
      shell: powershell
      run: |
        # Change encoding to display non-ASCII chars properly
        [Console]::InputEncoding = [System.Text.Encoding]::UTF8
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

        # Check Python version
        Write-Host "$(python --version)`n"

        # Run the launcher
        .\MIT-local-launcher.ps1 > $ErrorLogPath

        $ErrorLogPath = ".\Temp\log_errors-launcher-local.txt"
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                $ErrorLog
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run MIT-updater.ps1
      shell: powershell
      run: |
        Write-Host "$(python --version)`n"

        # Run the updater
        .\MIT-updater.ps1 > $ErrorLogPath

        $ErrorLogPath = ".\Temp\log_errors-launcher-local.txt"
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                $ErrorLog
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run MIT-local-webtoon-launcher.ps1
      shell: powershell
      run: |
        Write-Host "$(python --version)`n"

        $translatedFolder = ".\my_tools\test\manga\RAW-translated"

        if (Test-Path -Path $translatedFolder) {
            Remove-Item -Path $translatedFolder -Recurse -Force -Confirm:$false
        }

        # Run the launcher
        .\MIT-local-webtoon-launcher.ps1 > $ErrorLogPath

        $ErrorLogPath = ".\Temp\log_errors-launcher-local.txt"
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                $ErrorLog
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    # - name: Run MIT-web-launcher.ps1
    #   shell: powershell
    #   run: |
    #     Write-Host "$(python --version)`n"

    #     # Run the launcher
    #     $timeoutSeconds = 30
    #     $timer = [Diagnostics.Stopwatch]::StartNew()

    #     while ($timer.Elapsed.TotalSeconds -lt $timeoutSeconds) {
    #       .\MIT-web-launcher.ps1 > $ErrorLogPath
    #       Start-Sleep -Milliseconds 100
    #       if ($timer.Elapsed.TotalSeconds -eq $timeoutSeconds) {
    #         break
    #       }
    #     }

    #     $timer.Stop()

    #     $ErrorLogPath = ".\Temp\log_errors-launcher-local.txt"
        
    #     if (Test-Path -Path $ErrorLogPath) {
    #         $ErrorLog = Get-Content -Path $ErrorLogPath
    #         if ($ErrorLog -match "Error") {
    #             $ErrorLog
    #             Throw "`nError Found in '$ErrorLogPath'!"
    #         }
    #     }