name: Test Scripts

on:
  push:
    branches: 
      - main
    paths:
      - ".github/workflows/*"
      - "manga_translator/*"
      - "my_tools/*"
      - "MIT*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Modify variables for testing
      shell: powershell
      run: |
        # Disable Clear-HostLine in downloader.psm1
        $downloaderPath = ".\my_tools\downloader.psm1"

        $oldString = @"
            Clear-HostLine $Line
        "@

        $newString = @"
            # Clear-HostLine $Line
        "@

        (Get-Content -Path $downloaderPath -Raw) -replace $oldString, $newString | Set-Content -Path $downloaderPath

        # Replace my-config.json
        Copy-Item -Path ".\my_tools\test\my-config.json" -Destination ".\examples\" -Recurse -Force

        # Replace folder selection with plain path string
        $filePath = @(
            ".\MIT-local-launcher.ps1",
            ".\MIT-local-webtoon-launcher.ps1"
        )

        $findPattern = @"
        (?s)Select folder with FolderBrowserDialog.*Activate Python venv with another PowerShell script
        "@

        $replaceText = @'

            $InputPath = ".\my_tools\test\manga\RAW"

        '@

        foreach ($path in $filePath) {
            (Get-Content -Path $path -Raw) -replace $findPattern, $replaceText | Set-Content -Path $path
        }

        # Replace keypress input with plain character string
        $filePath = ".\MIT-web-launcher.ps1"

        $searchString = @'
        (?s)while\ \(\$process\.HasExited.*KeyChar\ -eq\ "Q"
        '@

        $replaceString = @'
        Start-Sleep -Seconds 120

            while ($process.HasExited -eq $false) {
                $key = "q"
                if ($key -eq "q"
        '@

        (Get-Content -Path $filePath -Raw) -replace $searchString, $replaceString | Set-Content -Path $filePath

    - name: Run MIT-installer.ps1
      shell: powershell
      run: |
        # Change Execution Policy for Pyenv Windows
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine

        # Check GitHub Actions Python version
        Write-Host "$(python --version)`n"

        Write-Host "$(where.exe python)`n"

        # Run the installer
        .\MIT-installer.ps1

        $ErrorLogPath = ".\Temp\log_errors-install.txt"

        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run MIT-local-launcher.ps1
      shell: powershell
      run: |
        # Change encoding to display non-ASCII chars properly
        $OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding

        # Check GitHub Actions Python version
        Write-Host "$(python --version)`n"

        # Run the launcher
        $ErrorLogPath = ".\Temp\log_errors-launcher-local.txt"

        .\MIT-local-launcher.ps1 > $ErrorLogPath
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run MIT-local-webtoon-launcher.ps1
      shell: powershell
      run: |
        # Change encoding to display non-ASCII chars properly
        $OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding

        # Check GitHub Actions Python version
        Write-Host "$(python --version)`n"

        # Delete previously translated images
        $translatedFolder = ".\my_tools\test\manga\RAW-translated"

        if (Test-Path -Path $translatedFolder) {
            Remove-Item -Path $translatedFolder -Recurse -Force -Confirm:$false
        }

        # Run the launcher
        $ErrorLogPath = ".\Temp\log_errors-launcher-local-webtoon.txt"

        .\MIT-local-webtoon-launcher.ps1 | Out-String -Stream | Write-Host > $ErrorLogPath
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run MIT-web-launcher.ps1
      shell: powershell
      run: |
        # Check GitHub Actions Python version
        Write-Host "$(python --version)`n"

        # Run the launcher
        $ErrorLogPath = ".\Temp\log_errors-launcher-web.txt"

        .\MIT-web-launcher.ps1 | Out-String -Stream | Write-Host > $ErrorLogPath

        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Run MIT-updater.ps1
      shell: powershell
      run: |
        # Check GitHub Actions Python version
        Write-Host "$(python --version)`n"

        # Run the updater
        .\MIT-updater.ps1 | Out-String -Stream | Write-Host > $ErrorLogPath

        $ErrorLogPath = ".\Temp\log_errors-launcher-local.txt"
        
        if (Test-Path -Path $ErrorLogPath) {
            $ErrorLog = Get-Content -Path $ErrorLogPath
            if ($ErrorLog -match "Error") {
                Throw "`nError Found in '$ErrorLogPath'!"
            }
        }

    - name: Check result folder
      shell: powershell
      run: |
        $result =  Get-ChildItem -Path ".\result" -Recurse | Where-Object { $_.Name -notlike "log_*.txt" }

        $result | Select-Object FullName

        if ($result) {
            Throw "Failed to Clean Up MIT result Folder!"
        } else {
            Write-Host "MIT result Folder Cleaned Up Successfully."
        }